name: Go

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Install geth
        run: |
          add-apt-repository -y ppa:ethereum/ethereum
          apt-get update
          apt-get install ethereum

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build binary
        run: make all

      - name: Fill tests
        run: ./rpctestgen
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.1

      - name: Lint
        run: make lint
